[theme]
# Primary accent color for interactive elements.
primaryColor = "#7e65a8"

# Background color for the main content area.
backgroundColor = "#3b3839"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#8ac6ff"

# Color used for almost all text.
textColor = "#fff"